
# Site settings
name: lucamazzone.github.io
title: Luca Mazzone
description: Assistant Professor of Economics at CERGE-EI
repo: https://github.com/lucamazzone/lucamazzone.github.io
url: https://lucamazzone.github.io
baseurl: /lucamazzone.github.io
google_analytics: UA-155998622-1
google-site-verification: dZbJAaEZ9uPqYDHfbz1xiqCo76-ru7jmZ9Na3yPA4iY

# Personal info
author: Luca Mazzone
first_name: Luca
last_name: Mazzone
university: University of Montreal
department: Economics
address: 3150 rue Jean-Brillant Montréal QC
office: C-6027
email: luca.mazzone@umontreal.ca
email2: luca.g.mazzone@gmail.com
phone: +1 2027714748310

# Icon settings
doi_icon: ai ai-doi
doi_title: DOI
data_icon: ai ai-open-data
data_title: Data
pdf_icon: fas fa-file-pdf
pdf_title: PDF
course_icon: fas fa-info-circle
course_title: Info
moodle_icon: ai ai-moodle-square
moodle_title: Moodle
link_icon: fas fa-external-link-square-alt
link_title: Link

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
