
# Site settings
name: eacabbi.github.io
title: Luca Mazzone
description: Economist at the International Monetary Fund
repo: https://github.com/lucamazzone/lucamazzone.github.io
url: https://lucamazzone.github.io
baseurl: /lucamazzone.github.io
google_analytics: UA-179129314-1
google-site-verification: EjDn9NB75Ybc73Rp6H3LzGkSFajoB4_PGmSHZUPYT3o

# Personal info
author: Luca Mazzone
first_name: Luca
last_name: Mazzone
university: International Monetary Fund
department: European Department
address: 720 19th Street, NW, Washington, DC
office:  
email: lmazzone@imf.org
email2: luca.g.mazzone@gmail.com

# Icon settings
doi_icon: ai ai-doi
doi_title: DOI
data_icon: ai ai-open-data
data_title: Data
pdf_icon: fas fa-file-pdf
pdf_title: PDF
course_icon: fas fa-info-circle
course_title: Info
moodle_icon: ai ai-moodle-square
moodle_title: Moodle
link_icon: fas fa-external-link-square-alt
link_title: Link

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
